CREATE DATABASE QUANLYTRAMXANG
GO

USE QUANLYTRAMXANG
GO

-------------------------------- TRAM XANG  --------------------------------------------
CREATE TABLE TRAMXANG
(
    MATRAMXANG CHAR(4) PRIMARY KEY, 
    TENTRAM VARCHAR(40) NOT NULL,
    VITRI VARCHAR(50) NOT NULL,
    SDT VARCHAR(20) NOT NULL
)
GO

--------------------------------- HANGHOA  --------------------------------------------
CREATE TABLE HANGHOA
(
    MAHANGHOA CHAR(4) PRIMARY KEY,
    TENHANGHOA VARCHAR(40) NOT NULL,
    DONVI VARCHAR(20),
    DONGIA MONEY NOT NULL
)
GO

--------------------------------- TRUBOM  ---------------------------------------------
CREATE TABLE TRUBOM 
(
    MATRU CHAR(4) PRIMARY KEY,
    MATRAMXANG CHAR(4) FOREIGN KEY REFERENCES TRAMXANG(MATRAMXANG),
    MAHANGHOA CHAR(4) FOREIGN KEY REFERENCES HANGHOA(MAHANGHOA),
    TENTRU VARCHAR(40) NOT NULL
)
GO

---------------------------------- GIAODICH  ---------------------------------------------
CREATE TABLE GIAODICH
(
    MAGIAODICH INT PRIMARY KEY,
    NGAYGIAODICH SMALLDATETIME,
    MATRAMXANG CHAR(4) FOREIGN KEY REFERENCES TRAMXANG(MATRAMXANG),
    MATRU CHAR(4) FOREIGN KEY REFERENCES TRUBOM(MATRU),
    MAHANGHOA CHAR(4) FOREIGN KEY REFERENCES HANGHOA(MAHANGHOA),
    SOLUONG DECIMAL(10, 2) NOT NULL,
    TONGDOANHTHU MONEY NOT NULL
)
GO
